export const PERMISSIONS = [
  "FORM_TEMPLATE_CREATE", "FORM_TEMPLATE_EDIT", "FORM_TEMPLATE_PUBLISH",
  "FORM_SUBMISSION_CREATE", "FORM_SUBMISSION_READ", "FORM_SUBMISSION_REVIEW", "FORM_SUBMISSION_APPROVE",
  "KNOWLEDGE_SEARCH", "KNOWLEDGE_ANALYTICS", "USER_MANAGE", "API_CLIENT_MANAGE", "SYSTEM_CONFIGURE"
] as const;
export type PermissionKey = (typeof PERMISSIONS)[number];
export const ROLE_DEFAULTS: Record<string, PermissionKey[]> = {
  EMPLOYEE: ["FORM_SUBMISSION_CREATE", "FORM_SUBMISSION_READ"],
  REVIEWER: ["FORM_SUBMISSION_READ", "FORM_SUBMISSION_REVIEW", "FORM_SUBMISSION_APPROVE"],
  FORM_MANAGER: ["FORM_TEMPLATE_CREATE", "FORM_TEMPLATE_EDIT", "FORM_TEMPLATE_PUBLISH", "FORM_SUBMISSION_READ"],
  KNOWLEDGE_MANAGER: ["FORM_SUBMISSION_READ", "KNOWLEDGE_SEARCH", "KNOWLEDGE_ANALYTICS"],
  ADMIN: [...PERMISSIONS],
};
