"use client";
import { useMemo,useState } from "react";import { useRouter } from "next/navigation";
type Field={id:string;key:string;label:string;description:string|null;fieldType:string;required:boolean;options:unknown;section:string|null};
type Value={fieldDefinitionId:string;valueJson:unknown;confirmedByUser:boolean;confidence:number|null};
type Message={id:string;role:string;content:string};
export function SubmissionWorkspace({submission}:{submission:{id:string;code:string;status:string;revision:number;formName:string;fields:Field[];values:Value[];messages:Message[]}}){const router=useRouter();const valueMap=useMemo(()=>new Map(submission.values.map(v=>[v.fieldDefinitionId,v])),[submission.values]);const[tab,setTab]=useState<"form"|"agent">("form");const[chat,setChat]=useState("");const[busy,setBusy]=useState(false);const locked=["SUBMITTED","UNDER_REVIEW","APPROVED","ARCHIVED"].includes(submission.status);
async function save(field:Field,value:unknown){setBusy(true);const r=await fetch(`/api/web/submissions/${submission.id}/fields`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({revision:submission.revision,updates:[{fieldId:field.id,value,confirmedByUser:true}]})});const j=await r.json();setBusy(false);if(!r.ok)alert(j.error?.message||"خطا");router.refresh();}
async function send(){if(!chat.trim())return;setBusy(true);const content=chat;setChat("");const r=await fetch(`/api/web/submissions/${submission.id}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content,clientMessageId:crypto.randomUUID()})});const j=await r.json();setBusy(false);if(!r.ok)alert(j.error?.message||"خطا");router.refresh();}
async function submit(){if(!confirm("فرم برای بازبینی ارسال شود؟"))return;setBusy(true);const r=await fetch(`/api/web/submissions/${submission.id}/submit`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({revision:submission.revision})});const j=await r.json();setBusy(false);if(!r.ok)alert(j.error?.code||"خطا");router.refresh();}
return <div><div className="workspace-head"><div><span className="badge">{submission.code}</span><h1>{submission.formName}</h1></div><span className={`status ${submission.status.toLowerCase()}`}>{submission.status}</span></div><div className="tabs"><button className={tab==="form"?"active":""} onClick={()=>setTab("form")}>فرم ساختاریافته</button><button className={tab==="agent"?"active":""} onClick={()=>setTab("agent")}>عامل گفت‌وگویی</button></div>{tab==="form"?<div className="panel form-panel">{submission.fields.map(field=><DynamicField key={field.id} field={field} value={valueMap.get(field.id)?.valueJson} confirmed={valueMap.get(field.id)?.confirmedByUser||false} locked={locked||busy} onSave={v=>save(field,v)}/>)}</div>:<div className="chat-layout"><div className="chat panel"><div className="messages">{submission.messages.map(m=><div key={m.id} className={`message ${m.role.toLowerCase()}`}><span>{m.role==="USER"?"شما":"عامل"}</span><p>{m.content}</p></div>)}{!submission.messages.length&&<div className="empty">برای شروع، اطلاعاتی درباره فرم بنویسید. عامل فقط داده‌هایی را که صریحاً بیان می‌کنید استخراج می‌کند.</div>}</div><div className="composer"><textarea value={chat} onChange={e=>setChat(e.target.value)} disabled={locked||busy} placeholder="پیام خود را بنویسید…"/><button className="btn primary" onClick={send} disabled={locked||busy||!chat.trim()}>ارسال</button></div></div><div className="panel live-values"><h2>مقادیر استخراج‌شده</h2>{submission.fields.map(f=>{const v=valueMap.get(f.id);return <div key={f.id}><span>{f.label}</span><strong>{renderValue(v?.valueJson)}</strong>{v?.confirmedByUser&&<small>تأیید کاربر</small>}</div>})}</div></div>}<div className="submit-bar"><span>ویرایش: {submission.revision}</span><button className="btn primary" disabled={locked||busy} onClick={submit}>ارسال برای بازبینی</button></div></div>}
function DynamicField({field,value,confirmed,locked,onSave}:{field:Field;value:unknown;confirmed:boolean;locked:boolean;onSave:(v:unknown)=>void}){const initial=Array.isArray(value)?value.map(String).join(", "):typeof value==="boolean"?String(value):typeof value==="string"||typeof value==="number"?String(value):value==null?"":JSON.stringify(value);const[v,setV]=useState<string>(initial);const options=Array.isArray(field.options)?field.options.map(String):[];let input:React.ReactNode;if(field.fieldType==="LONG_TEXT")input=<textarea value={v} onChange={e=>setV(e.target.value)} disabled={locked}/>;else if(field.fieldType==="BOOLEAN")input=<select value={v} onChange={e=>setV(e.target.value)} disabled={locked}><option value="">انتخاب…</option><option value="true">بله</option><option value="false">خیر</option></select>;else if(field.fieldType==="SINGLE_SELECT")input=<select value={v} onChange={e=>setV(e.target.value)} disabled={locked}><option value="">انتخاب…</option>{options.map(o=><option key={o}>{o}</option>)}</select>;else input=<input type={["NUMBER","INTEGER"].includes(field.fieldType)?"number":field.fieldType==="DATE"?"date":field.fieldType==="DATETIME"?"datetime-local":"text"} value={v} onChange={e=>setV(e.target.value)} disabled={locked}/>;return <div className="field-row"><label><span>{field.label}{field.required&&<b> *</b>}</span>{field.description&&<small>{field.description}</small>}{input}</label><div className="field-actions">{confirmed&&<span className="confirmed">تأییدشده</span>}<button className="btn secondary" disabled={locked} onClick={()=>{let out:unknown=v;if(field.fieldType==="BOOLEAN")out=v==="true";if(["NUMBER","INTEGER"].includes(field.fieldType))out=Number(v);if(["TAGS","MULTI_SELECT"].includes(field.fieldType))out=v.split(",").map(x=>x.trim()).filter(Boolean);onSave(out)}}>ذخیره</button></div></div>}
function renderValue(v:unknown){if(v===undefined||v===null||v==="")return "—";if(Array.isArray(v))return v.map(String).join(", ");if(typeof v==="object")return JSON.stringify(v);return String(v)}